# Generated by Django 5.2.14 on 2026-08-01 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('current_domain', models.CharField(db_index=True, max_length=70, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_token', models.CharField(blank=True, default='', max_length=64)),
                ('verification_token_expires', models.DateTimeField(blank=True, null=True)),
                ('verification_fail_count', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('banned', 'Banned')], db_index=True, default='active', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='profiles.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DomainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=70)),
                ('was_active_from', models.DateTimeField()),
                ('was_active_to', models.DateTimeField()),
                ('migration_type', models.CharField(choices=[('owner', 'Owner'), ('community', 'Community'), ('crawler', 'Crawler')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_history', to='profiles.onionprofile')),
            ],
            options={
                'verbose_name_plural': 'Domain histories',
                'ordering': ['-was_active_to'],
            },
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.onionprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='onionprofile',
            name='tags',
            field=models.ManyToManyField(related_name='profiles', through='profiles.ProfileTag', to='profiles.tag'),
        ),
        migrations.AddIndex(
            model_name='onionprofile',
            index=models.Index(fields=['status', 'is_verified'], name='profiles_on_status_d5381f_idx'),
        ),
        migrations.AddIndex(
            model_name='onionprofile',
            index=models.Index(fields=['category', 'status'], name='profiles_on_categor_9eaf44_idx'),
        ),
    ]
