# Generated by Django 5.2.14 on 2026-08-01 14:19

import django.db.models.deletion
import profiles.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_onionprofile_domainhistory_profiletag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('approved_edits', models.IntegerField(default=0)),
                ('rejected_edits', models.IntegerField(default=0)),
                ('trust_level', models.IntegerField(choices=[(0, 'ANONYMOUS'), (1, 'NEW'), (2, 'TRUSTED'), (3, 'MODERATOR')], default=profiles.constants.TrustLevel['ANONYMOUS'])),
                ('is_banned', models.BooleanField(default=False)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='profiles_co_user_id_9f8d73_idx'), models.Index(fields=['session_key'], name='profiles_co_session_a9d96d_idx'), models.Index(fields=['trust_level'], name='profiles_co_trust_l_89ed6f_idx')],
            },
        ),
    ]
