# Generated by Django 5.2.14 on 2026-08-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_domain', models.CharField(db_index=True, max_length=70)),
                ('new_domain', models.CharField(max_length=70)),
                ('source', models.CharField(choices=[('owner', 'Owner'), ('community', 'Community'), ('crawler', 'Crawler')], max_length=20)),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_reports', to='profiles.onionprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_migrations', to='profiles.contributor')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_migrations', to='profiles.contributor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='profiles_mi_status_522333_idx'), models.Index(fields=['old_domain'], name='profiles_mi_old_dom_df7027_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='profiles.onionprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edits', to='profiles.contributor')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_edits', to='profiles.contributor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='profiles_pr_status_c87575_idx'), models.Index(fields=['profile', 'status'], name='profiles_pr_profile_952146_idx')],
            },
        ),
    ]
