# Generated by Django 5.2.14 on 2026-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_migrationreport_profileedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='onionprofile',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='onionprofile',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onionprofile',
            name='response_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onionprofile',
            name='screenshot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
